source: .
destination: ./_site
layouts_dir: ./_layouts
keep_files: ['.git']
excerpt_separator: '<!-- more -->'

exclude: ['README.md']
include: ['.well-known']
gems: [jekyll-paginate]

markdown: kramdown
markdown_ext: md

paginate: 4

