source: .
destination: ./_site
layouts: ./_layouts
keep_files: ['.git']
excerpt_separator: '<!-- more -->'

exclude: ['README.md']
include: ['.well-known']

markdown: kramdown
markdown_ext: md

paginate: 4

