source: .
destination: ./_site
layouts: ./_layouts
keep_files: ['.git']

exclude: ['README.md', 'Dockerfile']

show_drafts: nil
limit_posts: 0

relative_permalinks: true
permalink: date
paginate_path: 'page:num'

markdown: kramdown
markdown_ext: md

host: 0.0.0.0
port: 4000
baseurl: /
