source: .
destination: ./_site
layouts: ./_layouts
keep_files: ['.git']
excerpt_separator: '<!-- more -->'

exclude: ['README.md', 'Dockerfile']
include: ['.well-known']

markdown: kramdown
markdown_ext: md
